### ISSUE TITLE
Unclear wording 'Do you beat your rival?'

### ISSUE THREAD

**Issue by aahaselgrove** [waschinski/rivalquack#4]
Thanks for making this great app! One recommendation would be to change the wording 'Do you beat your rival?' to something which makes it more clear that you get to roll the die on a tie, eg. 'Do you catch your rival?'?

**Comment by waschinski** [comment]
Thanks for your kind words and your recommendation. The wording change has just been deployed along with updates to the framework. As always, your browser caching files might get in your way for a while.
